export const APP_ACTIONS = {
  CHANGE_LOCALE: 'CHANGE_LOCALE'
};

export const SESSION_ACTIONS = {
  SET_ALERT: 'SET_ALERT',
  LOGOUT: 'LOGOUT',
  LOGIN_FAIL: 'LOGIN_FAIL',
  SET_USER_DETAILS: 'SET_USER_DETAILS'
};
