export const APP_ACTIONS = {
  CHANGE_LOCALE: 'CHANGE_LOCALE',
};

export const SESSION_ACTIONS = {
  LOGOUT: 'LOGOUT',
  LOGIN_FAIL: 'LOGIN_FAIL',
  CLEAR_USER: 'CLEAR_USER',
  SET_USER_DETAILS: 'SET_USER_DETAILS',
};
